export const languages = {
  it: { name: 'Italiano', path: '/' },
  en: { name: 'English', path: '/en/' },
  es: { name: 'Español', path: '/es/' },
};

export const content = {
  it: {
    title: 'A casa di Massi — Sentirsi a casa, in Sicilia',
    description: 'Una casa di famiglia a Frigintini, Modica. Quattro ospiti, spazi privati e un’accoglienza personale, tra i colori della campagna siciliana.',
    skip: 'Vai al contenuto', navigation: 'Navigazione principale', language: 'Scegli la lingua',
    menu: 'Apri il menu', closeMenu: 'Chiudi il menu',
    nav: ['La casa', 'Vivere il posto', 'Il territorio', 'Dove siamo'],
    book: 'Vieni a trovarci', bookShort: 'Prenota',
    eyebrow: 'FRIGINTINI, MODICA · SICILIA',
    hero: ['La Sicilia,', 'come a casa.'],
    heroText: 'La luce entra, la giornata può aspettare. Una casa nella campagna di Modica, da vivere con i tuoi tempi.',
    discover: 'Entra in casa', heroNote: 'Qualche giorno al tuo ritmo.',
    heroCaption: 'Una porta aperta sulla campagna.',
    introLabel: 'BENVENUTI A CASA DI MASSI',
    intro: 'Ci sono posti da visitare.\nE posti in cui sentirsi a casa.',
    introText: 'Un tavolo all’aperto, tocchi di colore, la pietra scaldata dal sole. Qui puoi posare le borse, prendere fiato e cominciare dalle cose che ti fanno stare bene.',
    houseLabel: '01 / LA CASA', houseTitle: 'Il tuo spazio,\nil tuo ritmo.',
    houseText: 'Cucina quando vuoi, fermati in cortile, ritrova i tuoi spazi a fine giornata. La casa è indipendente e accoglie fino a quattro persone, con uno spazio privato e accesso al resto della proprietà.',
    facts: [['house', 'Casa indipendente'], ['people', 'Fino a 4 ospiti'], ['sun', 'Spazio privato']],
    gallery: 'Guarda le foto', galleryLabel: 'Galleria della casa',
    photoOpen: 'Ingrandisci la foto:', galleryClose: 'Chiudi la galleria', galleryPrevious: 'Foto precedente', galleryNext: 'Foto successiva', photoOf: 'di',
    captions: { pane: 'Pane in un cesto', casa: 'La casa e i suoi colori', cucina: 'La cucina e il soppalco', camera: 'La camera da letto', cortile: 'Il cortile, all’ombra dell’albero', dettagli: 'Piccoli dettagli di casa', amaca: 'Un’amaca tra gli alberi', orto: 'Il verde dell’orto', bici: 'Le bici e i colori della casa', campagna: 'La campagna della proprietà', pietra: 'La pietra e la storia', bagno: 'Il bagno', soppalco: 'La zona notte sul soppalco' },
    alt: { pane: 'Pane dalla crosta dorata in un cesto foderato con un telo bianco', casa: 'Ingresso della casa con pergolato, piante e un murale giallo e turchese', cucina: 'Cucina luminosa con isola, travi di legno e scala turchese verso il soppalco', camera: 'Camera con letto matrimoniale, copriletto a fiori blu e porta aperta sulla luce', cortile: 'Tavolo e sedie colorate nel cortile di pietra sotto un albero', dettagli: 'Una ciotola di limoni sul tavolo della cucina', amaca: 'Amaca turchese all’ombra degli alberi nella proprietà', orto: 'Orto verde delimitato da muretti in pietra', bici: 'Biciclette appoggiate davanti al murale colorato della casa', campagna: 'Alberi e prato della proprietà sotto un cielo azzurro con nuvole', pietra: 'Piccolo edificio in pietra e cortile della proprietà', bagno: 'Bagno con doccia, lavabo e finestra', soppalco: 'Letto sul soppalco con travi a vista e ringhiera turchese' },
    lifeLabel: '02 / VIVERE IL POSTO', lifeTitle: 'Le cose semplici.\nQuelle che restano.',
    lifeText: 'Preparare qualcosa di buono, stare fuori più del previsto, cambiare idea sui programmi. Le giornate qui lasciano spazio anche a questo.',
    lifeCards: [
      { image: 'dettagli', title: 'Il tempo della tavola', text: 'Scegli cosa preparare, apparecchia e prenditi tutto il tempo che vuoi. La cucina e il barbecue sono a tua disposizione.' },
      { image: 'orto', title: 'Due passi nel verde', text: 'L’orto, le piante, un angolo all’ombra. C’è spazio per fare due passi o semplicemente restare fuori ancora un po’.' },
      { image: 'bici', title: 'Fuori, senza fretta', text: 'Le bici sono a disposizione per quando hai voglia di muoverti. Per il resto, puoi decidere giorno per giorno.' },
    ],
    hostLabel: 'L’ACCOGLIENZA', hostTitle: 'Il piacere\ndi accoglierti.',
    hostText: 'Un saluto, due chiacchiere, poi tutto il tempo per te. Massi ti accoglie e resta a disposizione, lasciandoti la libertà di scegliere quanto condividere e quando stare per conto tuo.',
    storyLabel: 'UNA CASA DI FAMIGLIA', storyTitle: 'Una casa,\nmolte storie.',
    storyText: 'È casa di famiglia, adibita anche alla cottura del pane in forno a legna. E quindi il ricordo dell’odore del pane.',
    territoryLabel: '03 / IL TERRITORIO', territoryTitle: 'Un po’ di Sicilia,\npartendo da qui.',
    territoryText: 'Le strade di Modica, una giornata al mare, la luce che cambia al mattino. Esci a scoprire questo angolo di Sicilia, poi torna a casa quando hai voglia di fermarti.',
    territoryTags: ['La luce dell’alba', 'Il mare', 'Le città barocche'],
    locationLabel: '04 / DOVE SIAMO', locationTitle: 'La prossima volta,\npassa da casa.',
    addressLabel: 'CI TROVI QUI', address: ['Via Calanchi 78', 'Frigintini, Modica', 'Sicilia, Italia'],
    map: 'Apri la mappa', stayLabel: 'IL TUO SOGGIORNO',
    stayText: 'Scegli quando venire. Su Airbnb trovi disponibilità, prezzi e dettagli del soggiorno. Se hai una domanda, puoi scrivere direttamente a Massi dall’annuncio.',
    airbnb: 'La casa su Airbnb', external: 'si apre in una nuova scheda',
    closing: 'Ci vediamo\nin Sicilia.',
    footer: 'Una casa. Una storia. Un po’ di Sicilia.', top: 'Torna su', privacy: 'Privacy',
    privacyTitle: 'Navigare con semplicità', privacyText: 'Questo sito non usa cookie, strumenti di analisi, moduli o contenuti esterni incorporati. Le foto e i caratteri sono serviti dal sito stesso. I link a Google Maps e Airbnb aprono siti esterni, soggetti alle rispettive informative. Il sito è ospitato su GitHub Pages: GitHub registra gli indirizzi IP dei visitatori per motivi di sicurezza.', close: 'Chiudi',
    notFound: 'Questa pagina non è di casa.', backHome: 'Torna alla casa',
  },
  en: {
    title: 'A casa di Massi — Feel at home in Sicily',
    description: 'A family home in Frigintini, Modica. Room for four, your own private space and a personal welcome in the colours of the Sicilian countryside.',
    skip: 'Skip to content', navigation: 'Main navigation', language: 'Choose your language',
    menu: 'Open menu', closeMenu: 'Close menu',
    nav: ['The house', 'Life here', 'Around us', 'Find us'], book: 'Come and stay', bookShort: 'Book',
    eyebrow: 'FRIGINTINI, MODICA · SICILY',
    hero: ['Sicily,', 'with a sense of home.'],
    heroText: 'Let the daylight in and take your time. A house in the Modica countryside, with room to settle into your own routine.',
    discover: 'Step inside', heroNote: 'A few days at your own pace.', heroCaption: 'A door onto the countryside.',
    introLabel: 'WELCOME TO A CASA DI MASSI',
    intro: 'Some places are for visiting.\nOthers feel like coming home.',
    introText: 'Touches of colour, sun-warmed stone and a table outside. Set down your bags, take a breath and find a corner that feels like yours.',
    houseLabel: '01 / THE HOUSE', houseTitle: 'Your own space.\nYour own pace.',
    houseText: 'Cook when you like, spend time in the courtyard and come back to your own space at the end of the day. The independent house sleeps up to four, with a private space and access to the rest of the property.',
    facts: [['house', 'Independent house'], ['people', 'Up to 4 guests'], ['sun', 'Private space']],
    gallery: 'Explore the photos', galleryLabel: 'House photo gallery', photoOpen: 'Enlarge photo:', galleryClose: 'Close gallery', galleryPrevious: 'Previous photo', galleryNext: 'Next photo', photoOf: 'of',
    captions: { pane: 'Bread in a basket', casa: 'The house and its colours', cucina: 'The kitchen and mezzanine', camera: 'The bedroom', cortile: 'The courtyard, beneath the tree', dettagli: 'The little things at home', amaca: 'A hammock among the trees', orto: 'The green of the vegetable garden', bici: 'Bikes and a splash of colour', campagna: 'Countryside on the property', pietra: 'Stone with a story', bagno: 'The bathroom', soppalco: 'The mezzanine sleeping area' },
    alt: { pane: 'Golden-crusted bread in a basket lined with a white cloth', casa: 'House entrance with a pergola, plants and a yellow and turquoise mural', cucina: 'Bright kitchen with an island, wooden beams and turquoise stairs to the mezzanine', camera: 'Bedroom with a double bed, blue floral bedspread and an open door letting in daylight', cortile: 'Colourful table and chairs in the stone courtyard beneath a tree', dettagli: 'A bowl of lemons on the kitchen table', amaca: 'Turquoise hammock in the shade of trees on the property', orto: 'Green vegetable garden bordered by stone walls', bici: 'Bicycles standing in front of the house’s colourful mural', campagna: 'Trees and grass on the property beneath a blue sky with clouds', pietra: 'Small stone building and courtyard on the property', bagno: 'Bathroom with a shower, basin and window', soppalco: 'Mezzanine bed beneath exposed beams, beside a turquoise railing' },
    lifeLabel: '02 / LIFE HERE', lifeTitle: 'The simple things.\nThe ones that stay.',
    lifeText: 'Cook something you like, stay outside a little longer, change your plans halfway through the day. There’s room for all of it here.',
    lifeCards: [
      { image: 'dettagli', title: 'Time around the table', text: 'Choose what to cook, set the table and take your time over it. The kitchen and barbecue are yours to use.' },
      { image: 'orto', title: 'A little time in the green', text: 'A vegetable garden, growing things and a patch of shade. Take a wander, or find a reason to stay outside a little longer.' },
      { image: 'bici', title: 'Outside, at your own pace', text: 'Bikes are available when you feel like heading out. Leave the rest of the day open, and decide as you go.' },
    ],
    hostLabel: 'A WARM HELLO', hostTitle: 'A personal\nwelcome.',
    hostText: 'A hello, a chat, then time to yourself. Massi welcomes you and is around if you need him. Whether you feel like company or a quiet afternoon on your own, there’s room for both.',
    storyLabel: 'A FAMILY HOME', storyTitle: 'A house with\nstories to tell.',
    storyText: 'It’s a family home that was also used for baking bread in a wood-fired oven. That’s where the memory of the smell of bread comes from.',
    territoryLabel: '03 / AROUND US', territoryTitle: 'Your own Sicily,\nstarting here.',
    territoryText: 'Wander through Modica, spend a day by the sea or head out in the first light. Take your time exploring this corner of Sicily. The house is here to come back to.',
    territoryTags: ['The light at sunrise', 'The sea', 'Baroque towns'],
    locationLabel: '04 / FIND US', locationTitle: 'Next time,\ncome over.',
    addressLabel: 'YOU’LL FIND US HERE', address: ['Via Calanchi 78', 'Frigintini, Modica', 'Sicily, Italy'],
    map: 'Open the map', stayLabel: 'YOUR STAY',
    stayText: 'Pick your dates. You’ll find availability, prices and details of your stay on Airbnb. If you have a question, you can message Massi directly through the listing.',
    airbnb: 'Find the house on Airbnb', external: 'opens in a new tab',
    closing: 'See you\nin Sicily.',
    footer: 'A house. A story. A little Sicily.', top: 'Back to top', privacy: 'Privacy',
    privacyTitle: 'A simple way to browse', privacyText: 'This site uses no cookies, analytics, forms or embedded third-party content. Photos and fonts are served by the site itself. Links to Google Maps and Airbnb open external websites, which have their own privacy policies. This site is hosted on GitHub Pages: GitHub logs visitor IP addresses for security purposes.', close: 'Close',
    notFound: 'This page isn’t at home.', backHome: 'Back to the house',
  },
  es: {
    title: 'A casa di Massi — Sentirse en casa, en Sicilia',
    description: 'Una casa familiar en Frigintini, Módica. Espacio para cuatro, intimidad y una acogida cercana entre los colores del campo siciliano.',
    skip: 'Ir al contenido', navigation: 'Navegación principal', language: 'Elige tu idioma',
    menu: 'Abrir menú', closeMenu: 'Cerrar menú',
    nav: ['La casa', 'La vida aquí', 'El entorno', 'Dónde estamos'], book: 'Ven a conocernos', bookShort: 'Reserva',
    eyebrow: 'FRIGINTINI, MÓDICA · SICILIA', hero: ['Sicilia,', 'como en casa.'],
    heroText: 'Deja entrar la luz y tómate tu tiempo. Una casa en el campo de Módica para disfrutar a tu manera.',
    discover: 'Pasa, estás en casa', heroNote: 'Unos días a tu aire.', heroCaption: 'Una puerta abierta al campo.',
    introLabel: 'BIENVENIDOS A CASA DI MASSI',
    intro: 'Hay lugares que se visitan.\nY otros que se sienten como casa.',
    introText: 'Una mesa al aire libre, pinceladas de color y la piedra al sol. Deja las maletas, respira y busca ese rincón en el que te apetezca quedarte un rato.',
    houseLabel: '01 / LA CASA', houseTitle: 'Tu espacio,\na tu ritmo.',
    houseText: 'Cocina cuando quieras, disfruta del patio y vuelve a tu propio espacio al terminar el día. La casa es independiente, tiene capacidad para cuatro personas y dispone de un espacio privado, con acceso al resto de la propiedad.',
    facts: [['house', 'Casa independiente'], ['people', 'Hasta 4 personas'], ['sun', 'Espacio privado']],
    gallery: 'Descubre las fotos', galleryLabel: 'Galería de la casa', photoOpen: 'Ampliar la foto:', galleryClose: 'Cerrar galería', galleryPrevious: 'Foto anterior', galleryNext: 'Foto siguiente', photoOf: 'de',
    captions: { pane: 'Pan en una cesta', casa: 'La casa y sus colores', cucina: 'La cocina y el altillo', camera: 'El dormitorio', cortile: 'El patio, a la sombra del árbol', dettagli: 'Pequeños detalles de casa', amaca: 'Una hamaca entre los árboles', orto: 'El verde del huerto', bici: 'Las bicis y los colores de la casa', campagna: 'El campo de la propiedad', pietra: 'Piedra con historia', bagno: 'El baño', soppalco: 'La zona de descanso en el altillo' },
    alt: { pane: 'Panes de corteza dorada en una cesta cubierta con un paño blanco', casa: 'Entrada de la casa con pérgola, plantas y un mural amarillo y turquesa', cucina: 'Cocina luminosa con isla, vigas de madera y escalera turquesa hacia el altillo', camera: 'Dormitorio con cama doble, colcha de flores azules y puerta abierta a la luz', cortile: 'Mesa y sillas de colores en el patio de piedra, bajo un árbol', dettagli: 'Un cuenco de limones sobre la mesa de la cocina', amaca: 'Hamaca turquesa a la sombra de los árboles de la propiedad', orto: 'Huerto verde rodeado de muros de piedra', bici: 'Bicicletas delante del mural de colores de la casa', campagna: 'Árboles y hierba de la propiedad bajo un cielo azul con nubes', pietra: 'Pequeña construcción de piedra y patio de la propiedad', bagno: 'Baño con ducha, lavabo y ventana', soppalco: 'Cama en el altillo bajo vigas de madera, junto a una barandilla turquesa' },
    lifeLabel: '02 / LA VIDA AQUÍ', lifeTitle: 'Las cosas sencillas.\nLas que se quedan.',
    lifeText: 'Preparar algo rico, quedarse fuera un rato más, cambiar de planes a mitad del día. Aquí también hay sitio para eso.',
    lifeCards: [
      { image: 'dettagli', title: 'Tiempo alrededor de la mesa', text: 'Elige qué cocinar, pon la mesa y disfruta sin mirar el reloj. La cocina y la barbacoa están a tu disposición.' },
      { image: 'orto', title: 'Un paseo entre el verde', text: 'El huerto, las plantas, un rincón a la sombra. Hay espacio para dar un paseo o simplemente quedarse al aire libre un poco más.' },
      { image: 'bici', title: 'Al aire libre, sin prisa', text: 'Tienes bicis a tu disposición para cuando te apetezca salir. Lo demás puedes decidirlo sobre la marcha.' },
    ],
    hostLabel: 'LA BIENVENIDA', hostTitle: 'El gusto\nde recibirte.',
    hostText: 'Un saludo, una charla y después tiempo para ti. Massi te recibe y está disponible si lo necesitas. Tú eliges cuándo compartir un rato y cuándo disfrutar de tu intimidad.',
    storyLabel: 'UNA CASA FAMILIAR', storyTitle: 'Una casa\ncon historia.',
    storyText: 'Es una casa de familia que también se utilizaba para cocer pan en un horno de leña. De ahí el recuerdo del olor del pan.',
    territoryLabel: '03 / EL ENTORNO', territoryTitle: 'Un poco de Sicilia,\nempezando por aquí.',
    territoryText: 'Pasea por Módica, dedica un día al mar o sal a ver la primera luz de la mañana. Descubre este rincón de Sicilia a tu aire, con una casa a la que volver.',
    territoryTags: ['La luz del amanecer', 'El mar', 'Las ciudades barrocas'],
    locationLabel: '04 / DÓNDE ESTAMOS', locationTitle: 'La próxima vez,\npasa por casa.',
    addressLabel: 'AQUÍ NOS ENCONTRARÁS', address: ['Via Calanchi 78', 'Frigintini, Modica', 'Sicilia, Italia'],
    map: 'Abrir el mapa', stayLabel: 'TU ESTANCIA',
    stayText: 'Elige cuándo venir. En Airbnb encontrarás disponibilidad, precios y detalles de la estancia. Si tienes alguna pregunta, puedes escribir directamente a Massi desde el anuncio.',
    airbnb: 'La casa en Airbnb', external: 'se abre en una pestaña nueva',
    closing: 'Nos vemos\nen Sicilia.',
    footer: 'Una casa. Una historia. Un poco de Sicilia.', top: 'Volver arriba', privacy: 'Privacidad',
    privacyTitle: 'Navegar con sencillez', privacyText: 'Este sitio no utiliza cookies, herramientas de análisis, formularios ni contenido externo incrustado. Las fotos y las fuentes se sirven desde el propio sitio. Los enlaces a Google Maps y Airbnb abren sitios externos con sus propias políticas de privacidad. Este sitio está alojado en GitHub Pages: GitHub registra las direcciones IP de los visitantes por motivos de seguridad.', close: 'Cerrar',
    notFound: 'Esta página no está en casa.', backHome: 'Volver a la casa',
  },
};
