export const languages = {
  it: { name: 'Italiano', path: '/' },
  en: { name: 'English', path: '/en/' },
  es: { name: 'Español', path: '/es/' },
};

export const content = {
  it: {
    title: 'A casa di Massi — Casa per quattro a Frigintini, Modica',
    description: 'Una casa indipendente per quattro nella campagna di Modica, con cucina, cortile e spazi privati. Scopri la casa di famiglia e l’accoglienza di Massi.',
    skip: 'Vai al contenuto', navigation: 'Navigazione principale', language: 'Scegli la lingua',
    menu: 'Apri il menu', closeMenu: 'Chiudi il menu',
    nav: ['La casa', 'Vivere il posto', 'Il territorio', 'Dove siamo'],
    book: 'Disponibilità', bookShort: 'Prenota',
    eyebrow: 'FRIGINTINI, MODICA · SICILIA',
    hero: ['La tua casa,', 'a Modica.'],
    heroText: 'A Frigintini, una casa di famiglia per quattro persone, con la cucina, un cortile e uno spazio privato. Un punto di partenza per conoscere la Sicilia e una casa da ritrovare al ritorno.',
    discover: 'Scopri la casa', heroNote: 'Casa indipendente · Fino a 4 ospiti',
    heroCaption: 'Il pergolato e il murale all’ingresso.',
    introLabel: 'BENVENUTI A CASA DI MASSI',
    intro: 'La scala turchese.\nIl tavolo sotto l’albero.',
    introText: 'Sono i dettagli che riconoscerai appena arrivi: le travi di legno sopra la cucina, i colori del murale, il cortile in pietra. A casa di Massi ha una storia di famiglia e spazi da abitare, anche quando ti fermi solo per qualche giorno.',
    houseLabel: '01 / LA CASA', houseTitle: 'Dentro casa,\nfuori in cortile.',
    houseText: 'La cucina si apre sotto il soppalco, raggiunto dalla scala turchese. Ci sono una camera da letto e una zona notte al piano superiore; fuori, il tavolo in cortile. La casa accoglie fino a quattro ospiti, è indipendente e ha un proprio spazio privato, con accesso anche al resto della proprietà.',
    facts: [['house', 'Casa indipendente'], ['people', 'Fino a 4 ospiti'], ['sun', 'Spazio privato']],
    gallery: 'Guarda le foto', galleryLabel: 'Galleria della casa',
    photoOpen: 'Ingrandisci la foto:', galleryClose: 'Chiudi la galleria', galleryPrevious: 'Foto precedente', galleryNext: 'Foto successiva', photoOf: 'di',
    captions: { 'cucina-ampia': 'La cucina e la tavola', 'limoni': 'Limoni sul tavolo della cucina', 'erbe': 'Le erbe in cucina', 'tavola': 'La tavola in cortile', 'giardino': 'La casa tra gli alberi', 'esterno': 'I colori della casa', forno: 'La maidda', impasto: 'Lavorazione dell’impasto', lievitazione: 'L’impasto durante la lievitazione', pane: 'Pane in un cesto', casa: 'Il pergolato e il murale all’ingresso', cucina: 'La cucina sotto il soppalco', camera: 'La camera da letto', cortile: 'Il tavolo in cortile, sotto l’albero', dettagli: 'La tavola all’ombra dell’albero', amaca: 'Un’amaca tra gli alberi', orto: 'L’orto della proprietà', bici: 'Le biciclette davanti al murale', campagna: 'La campagna della proprietà', pietra: 'Il cortile e l’edificio in pietra', bagno: 'Il bagno', soppalco: 'La zona notte sul soppalco' },
    alt: { 'cucina-ampia': 'Vista della cucina con isola, tavolo, travi di legno e pavimento decorato', 'limoni': 'Cesto di limoni accanto a una tazza sul tavolo della cucina', 'erbe': 'Rametti di rosmarino ed erbe fiorite in vasi davanti alle piastrelle della cucina', 'tavola': 'Bicchieri, una bottiglia e un cesto di noci sul tavolo apparecchiato in cortile', 'giardino': 'Casa con murale vista tra gli ulivi e una catasta di legna', 'esterno': 'Vista della casa con murale colorato e biciclette davanti all’ingresso', apertura: 'Ingresso della casa con pergolato verde, giardino e murale colorato', forno: 'Maidda in legno davanti al forno a legna acceso', impasto: 'Una persona lavora l’impasto sul tavolo davanti al forno a legna', lievitazione: 'Pagnotte di impasto adagiate sotto un telo a quadri', pane: 'Pane dalla crosta dorata in un cesto foderato con un telo bianco', casa: 'Ingresso della casa con pergolato, piante e un murale giallo e turchese', cucina: 'Cucina luminosa con isola, travi di legno e scala turchese verso il soppalco', camera: 'Camera con letto matrimoniale, copriletto a fiori blu e porta aperta sulla luce', cortile: 'Tavolo e sedie colorate nel cortile di pietra sotto un albero', dettagli: 'Tavolo apparecchiato e sedie colorate nel cortile sotto un albero', amaca: 'Amaca turchese all’ombra degli alberi nella proprietà', orto: 'Orto verde delimitato da muretti in pietra', bici: 'Biciclette appoggiate davanti al murale colorato della casa', campagna: 'Alberi e prato della proprietà sotto un cielo azzurro con nuvole', pietra: 'Piccolo edificio in pietra e cortile della proprietà', bagno: 'Bagno con doccia, lavabo e finestra', soppalco: 'Letto sul soppalco con travi a vista e ringhiera turchese' },
    lifeLabel: '02 / VIVERE IL POSTO', lifeTitle: 'Cucina, orto\ne vita all’aperto.',
    lifeText: 'Puoi preparare i pasti in casa, usare il barbecue o uscire in bici. Il cortile, l’orto e gli alberi fanno parte del soggiorno quanto gli interni: vale la pena conoscerli anche nei giorni in cui resti qui.',
    outdoorTitle: 'Intorno alla casa',
    lifeCards: [
      { image: 'dettagli', title: 'Dalla cucina al cortile', text: 'La cucina è a tua disposizione per i pasti di ogni giorno. Puoi apparecchiare al tavolo all’aperto; per cucinare fuori, c’è anche il barbecue.' },
      { image: 'orto', title: 'Tra l’orto e gli alberi', text: 'Oltre al tuo spazio privato, puoi accedere al resto della proprietà. Ci sono l’orto, gli alberi e l’amaca: angoli diversi da conoscere durante il soggiorno.' },
      { image: 'bici', title: 'Un’uscita in bici', text: 'Le biciclette sono a disposizione degli ospiti. Se vuoi usarle durante il soggiorno, puoi chiedere a Massi prima di partire.' },
    ],
    hostLabel: 'CHI TI ACCOGLIE', hostTitle: 'A riceverti\nc’è Massi.',
    hostText: 'Massi è presente e disponibile, ma lascia a te la scelta di quanto condividere. Puoi fermarti a chiacchierare o tenere le giornate tutte per te: la tua privacy fa parte dell’accoglienza.',
    storyLabel: 'UN RICORDO DI FAMIGLIA', storyTitle: 'Il profumo\ndel pane.',
    storyText: 'È casa di famiglia, adibita anche alla cottura del pane in forno a legna. E quindi il ricordo dell’odore del pane.',
    territoryLabel: '03 / IL TERRITORIO', territoryTitle: 'Modica, il mare,\nle città barocche.',
    territoryText: 'La casa si trova a Frigintini, nella campagna di Modica. Da qui puoi dedicare le giornate alle città barocche e al mare, oppure cominciare dall’alba e dal paesaggio intorno alla proprietà. Al ritorno, ritrovi il cortile e la tua casa.',
    territoryTags: ['La luce dell’alba', 'Il mare', 'Le città barocche'],
    locationLabel: '04 / DOVE SIAMO', locationTitle: 'Il tuo soggiorno\na Frigintini.',
    addressLabel: 'CI TROVI QUI', address: ['Via Calanchi 78', 'Frigintini, Modica', 'Sicilia, Italia'],
    map: 'Apri la mappa', stayLabel: 'IL TUO SOGGIORNO',
    stayText: 'Su Airbnb puoi consultare le date disponibili, i prezzi e le informazioni sul soggiorno. Prima di prenotare, puoi scrivere a Massi dall’annuncio per le domande sulla casa.',
    airbnb: 'Disponibilità su Airbnb', external: 'si apre in una nuova scheda',
    closing: 'Ti aspettiamo\na Frigintini.',
    footer: 'Una casa di famiglia nella campagna di Modica.', top: 'Torna su', privacy: 'Privacy',
    privacyTitle: 'Navigare con semplicità', privacyText: 'Questo sito non usa cookie, strumenti di analisi, moduli o contenuti esterni incorporati. Le foto e i caratteri sono serviti dal sito stesso. I link a Google Maps e Airbnb aprono siti esterni, soggetti alle rispettive informative. Il sito è ospitato su GitHub Pages: GitHub registra gli indirizzi IP dei visitatori per motivi di sicurezza.', close: 'Chiudi',
    notFound: 'Questa pagina non è di casa.', backHome: 'Torna alla casa',
  },
  en: {
    title: 'A casa di Massi — A house for four in Frigintini, Modica',
    description: 'An independent house for four in the Modica countryside, with a kitchen, courtyard and private space. Discover the family home and meet your host, Massi.',
    skip: 'Skip to content', navigation: 'Main navigation', language: 'Choose your language',
    menu: 'Open menu', closeMenu: 'Close menu',
    nav: ['The house', 'Life here', 'Around us', 'Find us'], book: 'Availability', bookShort: 'Book',
    eyebrow: 'FRIGINTINI, MODICA · SICILY',
    hero: ['Your home', 'in Modica.'],
    heroText: 'A family home in Frigintini, with room for four, a kitchen, a courtyard and your own private space. Stay here to explore Sicily, with a house to come back to at the end of the day.',
    discover: 'See the house', heroNote: 'Independent house · Up to 4 guests', heroCaption: 'The pergola and mural by the entrance.',
    introLabel: 'WELCOME TO A CASA DI MASSI',
    intro: 'Turquoise stairs.\nThe courtyard table.',
    introText: 'You’ll recognise them when you arrive: the wooden beams above the kitchen, the colours of the mural, the stone courtyard. This is a family home, with spaces you can make use of even if you’re only staying a few days.',
    houseLabel: '01 / THE HOUSE', houseTitle: 'Inside the house,\nout in the courtyard.',
    houseText: 'The kitchen sits below the mezzanine, reached by the turquoise stairs. There’s a bedroom and an upstairs sleeping area, with a table outside in the courtyard. The independent house sleeps up to four and has its own private space. Guests can also use the rest of the property.',
    facts: [['house', 'Independent house'], ['people', 'Up to 4 guests'], ['sun', 'Private space']],
    gallery: 'Explore the photos', galleryLabel: 'House photo gallery', photoOpen: 'Enlarge photo:', galleryClose: 'Close gallery', galleryPrevious: 'Previous photo', galleryNext: 'Next photo', photoOf: 'of',
    captions: { 'cucina-ampia': 'The kitchen and dining table', 'limoni': 'Lemons on the kitchen table', 'erbe': 'Herbs in the kitchen', 'tavola': 'The courtyard table', 'giardino': 'The house among the trees', 'esterno': 'The colours of the house', forno: 'The maidda', impasto: 'Working the dough', lievitazione: 'Dough left to rise', pane: 'Bread in a basket', casa: 'The pergola and mural by the entrance', cucina: 'The kitchen below the mezzanine', camera: 'The bedroom', cortile: 'The courtyard table beneath the tree', dettagli: 'The table beneath the tree', amaca: 'A hammock among the trees', orto: 'The vegetable garden on the property', bici: 'Bicycles beside the mural', campagna: 'Countryside on the property', pietra: 'The courtyard and stone building', bagno: 'The bathroom', soppalco: 'The mezzanine sleeping area' },
    alt: { 'cucina-ampia': 'Kitchen with an island, dining table, wooden beams and patterned floor', 'limoni': 'Basket of lemons beside a cup on the kitchen table', 'erbe': 'Rosemary sprigs and flowering herbs in vases in front of the kitchen tiles', 'tavola': 'Glasses, a bottle and a basket of walnuts on the set courtyard table', 'giardino': 'House and mural seen between olive trees and a stack of logs', 'esterno': 'View of the house with a colourful mural and bicycles by the entrance', apertura: 'House entrance with a leafy pergola, garden and colourful mural', forno: 'Wooden maidda in front of a lit wood-fired oven', impasto: 'A person working dough on a table in front of the wood-fired oven', lievitazione: 'Unbaked loaves resting beneath a checked cloth', pane: 'Golden-crusted bread in a basket lined with a white cloth', casa: 'House entrance with a pergola, plants and a yellow and turquoise mural', cucina: 'Bright kitchen with an island, wooden beams and turquoise stairs to the mezzanine', camera: 'Bedroom with a double bed, blue floral bedspread and an open door letting in daylight', cortile: 'Colourful table and chairs in the stone courtyard beneath a tree', dettagli: 'A set table and colourful chairs in the courtyard beneath a tree', amaca: 'Turquoise hammock in the shade of trees on the property', orto: 'Green vegetable garden bordered by stone walls', bici: 'Bicycles standing in front of the house’s colourful mural', campagna: 'Trees and grass on the property beneath a blue sky with clouds', pietra: 'Small stone building and courtyard on the property', bagno: 'Bathroom with a shower, basin and window', soppalco: 'Mezzanine bed beneath exposed beams, beside a turquoise railing' },
    lifeLabel: '02 / LIFE HERE', lifeTitle: 'The kitchen, garden\nand outdoors.',
    lifeText: 'Cook at home, use the barbecue or head out on a bike. The courtyard, vegetable garden and trees are as much a part of your stay as the rooms inside, with plenty to explore on days spent at the house.',
    outdoorTitle: 'Around the house',
    lifeCards: [
      { image: 'dettagli', title: 'Meals at home', text: 'The kitchen is yours to use for everyday meals. Set the table outside in the courtyard, or use the barbecue when you feel like cooking outdoors.' },
      { image: 'orto', title: 'Around the garden', text: 'You can explore the rest of the property as well as enjoy your own private space. There’s a vegetable garden, trees and a hammock to discover during your stay.' },
      { image: 'bici', title: 'Heading out by bike', text: 'Bicycles are available for guests to use. If you’d like to take them out during your stay, ask Massi before you set off.' },
    ],
    hostLabel: 'YOUR HOST', hostTitle: 'Massi is here\nto welcome you.',
    hostText: 'Massi is around if you need him and leaves you to choose how much company you’d like. Stop for a chat or spend the day on your own. Respect for your privacy is part of his welcome.',
    storyLabel: 'A FAMILY MEMORY', storyTitle: 'The smell\nof bread.',
    storyText: 'It’s a family home that was also used for baking bread in a wood-fired oven. That’s where the memory of the smell of bread comes from.',
    territoryLabel: '03 / AROUND US', territoryTitle: 'Modica, the sea\nand baroque towns.',
    territoryText: 'The house is in Frigintini, in the countryside around Modica. Spend your days visiting baroque towns or going to the sea, or start with sunrise and the landscape around the property. After a day out, return to the house and its courtyard.',
    territoryTags: ['The light at sunrise', 'The sea', 'Baroque towns'],
    locationLabel: '04 / FIND US', locationTitle: 'Plan your stay\nin Frigintini.',
    addressLabel: 'YOU’LL FIND US HERE', address: ['Via Calanchi 78', 'Frigintini, Modica', 'Sicily, Italy'],
    map: 'Open the map', stayLabel: 'YOUR STAY',
    stayText: 'You’ll find available dates, prices and details of the stay on Airbnb. Before booking, you can message Massi through the listing with questions about the house.',
    airbnb: 'Availability on Airbnb', external: 'opens in a new tab',
    closing: 'Come and stay\nin Frigintini.',
    footer: 'A family home in the Modica countryside.', top: 'Back to top', privacy: 'Privacy',
    privacyTitle: 'A simple way to browse', privacyText: 'This site uses no cookies, analytics, forms or embedded third-party content. Photos and fonts are served by the site itself. Links to Google Maps and Airbnb open external websites, which have their own privacy policies. This site is hosted on GitHub Pages: GitHub logs visitor IP addresses for security purposes.', close: 'Close',
    notFound: 'This page isn’t at home.', backHome: 'Back to the house',
  },
  es: {
    title: 'A casa di Massi — Casa para cuatro en Frigintini, Módica',
    description: 'Una casa independiente para cuatro en el campo de Módica, con cocina, patio y espacio privado. Conoce la casa familiar y a Massi, tu anfitrión.',
    skip: 'Ir al contenido', navigation: 'Navegación principal', language: 'Elige tu idioma',
    menu: 'Abrir menú', closeMenu: 'Cerrar menú',
    nav: ['La casa', 'La vida aquí', 'El entorno', 'Dónde estamos'], book: 'Disponibilidad', bookShort: 'Reserva',
    eyebrow: 'FRIGINTINI, MÓDICA · SICILIA', hero: ['Tu casa', 'en Módica.'],
    heroText: 'Una casa familiar en Frigintini para cuatro personas, con cocina, patio y un espacio privado. Desde aquí puedes salir a conocer Sicilia y volver a casa al terminar el día.',
    discover: 'Conoce la casa', heroNote: 'Casa independiente · Hasta 4 personas', heroCaption: 'La pérgola y el mural de la entrada.',
    introLabel: 'BIENVENIDOS A CASA DI MASSI',
    intro: 'La escalera turquesa.\nLa mesa bajo el árbol.',
    introText: 'Los reconocerás al llegar: las vigas de madera sobre la cocina, los colores del mural, el patio de piedra. A casa di Massi es una casa familiar con espacios que puedes hacer tuyos, aunque solo te quedes unos días.',
    houseLabel: '01 / LA CASA', houseTitle: 'Dentro de casa,\nfuera en el patio.',
    houseText: 'Sobre la cocina está el altillo, al que se sube por la escalera turquesa. Hay un dormitorio y una zona para dormir en la planta superior; fuera, una mesa en el patio. La casa es independiente, tiene capacidad para cuatro personas y cuenta con su propio espacio privado, además de acceso al resto de la propiedad.',
    facts: [['house', 'Casa independiente'], ['people', 'Hasta 4 personas'], ['sun', 'Espacio privado']],
    gallery: 'Descubre las fotos', galleryLabel: 'Galería de la casa', photoOpen: 'Ampliar la foto:', galleryClose: 'Cerrar galería', galleryPrevious: 'Foto anterior', galleryNext: 'Foto siguiente', photoOf: 'de',
    captions: { 'cucina-ampia': 'La cocina y la mesa', 'limoni': 'Limones en la mesa de la cocina', 'erbe': 'Las hierbas en la cocina', 'tavola': 'La mesa del patio', 'giardino': 'La casa entre los árboles', 'esterno': 'Los colores de la casa', forno: 'La maidda', impasto: 'Preparación de la masa', lievitazione: 'La masa durante la fermentación', pane: 'Pan en una cesta', casa: 'La pérgola y el mural de la entrada', cucina: 'La cocina bajo el altillo', camera: 'El dormitorio', cortile: 'La mesa del patio, bajo el árbol', dettagli: 'La mesa a la sombra del árbol', amaca: 'Una hamaca entre los árboles', orto: 'El huerto de la propiedad', bici: 'Las bicicletas delante del mural', campagna: 'El campo de la propiedad', pietra: 'El patio y la construcción de piedra', bagno: 'El baño', soppalco: 'La zona de descanso en el altillo' },
    alt: { 'cucina-ampia': 'Cocina con isla, mesa, vigas de madera y suelo decorado', 'limoni': 'Cesta de limones junto a una taza en la mesa de la cocina', 'erbe': 'Ramas de romero y hierbas con flores en jarrones delante de los azulejos de la cocina', 'tavola': 'Copas, una botella y una cesta de nueces sobre la mesa puesta en el patio', 'giardino': 'Casa con mural vista entre olivos y una pila de leña', 'esterno': 'Vista de la casa con mural de colores y bicicletas delante de la entrada', apertura: 'Entrada de la casa con pérgola cubierta de plantas, jardín y mural de colores', forno: 'Maidda de madera delante del horno de leña encendido', impasto: 'Una persona trabaja la masa sobre una mesa delante del horno de leña', lievitazione: 'Panes de masa reposando bajo un paño de cuadros', pane: 'Panes de corteza dorada en una cesta cubierta con un paño blanco', casa: 'Entrada de la casa con pérgola, plantas y un mural amarillo y turquesa', cucina: 'Cocina luminosa con isla, vigas de madera y escalera turquesa hacia el altillo', camera: 'Dormitorio con cama doble, colcha de flores azules y puerta abierta a la luz', cortile: 'Mesa y sillas de colores en el patio de piedra, bajo un árbol', dettagli: 'Mesa puesta y sillas de colores en el patio bajo un árbol', amaca: 'Hamaca turquesa a la sombra de los árboles de la propiedad', orto: 'Huerto verde rodeado de muros de piedra', bici: 'Bicicletas delante del mural de colores de la casa', campagna: 'Árboles y hierba de la propiedad bajo un cielo azul con nubes', pietra: 'Pequeña construcción de piedra y patio de la propiedad', bagno: 'Baño con ducha, lavabo y ventana', soppalco: 'Cama en el altillo bajo vigas de madera, junto a una barandilla turquesa' },
    lifeLabel: '02 / LA VIDA AQUÍ', lifeTitle: 'Cocina, huerto\ny aire libre.',
    lifeText: 'Puedes preparar la comida en casa, usar la barbacoa o salir en bici. El patio, el huerto y los árboles también forman parte de la estancia: hay rincones por conocer en los días que pases aquí.',
    outdoorTitle: 'Alrededor de la casa',
    lifeCards: [
      { image: 'dettagli', title: 'De la cocina al patio', text: 'La cocina está a tu disposición para las comidas de cada día. Puedes poner la mesa fuera, en el patio, y usar la barbacoa si te apetece cocinar al aire libre.' },
      { image: 'orto', title: 'Entre el huerto y los árboles', text: 'Además de disfrutar de tu espacio privado, puedes recorrer el resto de la propiedad. El huerto, los árboles y la hamaca son algunos de los rincones que encontrarás durante tu estancia.' },
      { image: 'bici', title: 'Un paseo en bici', text: 'Hay bicicletas a disposición de los huéspedes. Si quieres usarlas durante tu estancia, puedes hablar con Massi antes de salir.' },
    ],
    hostLabel: 'TU ANFITRIÓN', hostTitle: 'Massi te da\nla bienvenida.',
    hostText: 'Massi está presente y disponible, y tú decides cuánto te apetece compartir. Puedes quedarte a charlar o pasar el día por tu cuenta. Respetar tu intimidad es parte de su manera de recibirte.',
    storyLabel: 'UN RECUERDO FAMILIAR', storyTitle: 'El olor\ndel pan.',
    storyText: 'Es una casa de familia que también se utilizaba para cocer pan en un horno de leña. De ahí el recuerdo del olor del pan.',
    territoryLabel: '03 / EL ENTORNO', territoryTitle: 'Módica y\nla Sicilia barroca.',
    territoryText: 'La casa está en Frigintini, en el campo de Módica. Puedes dedicar los días a conocer las ciudades barrocas o a ir al mar, o empezar por el amanecer y el paisaje de la propiedad. A la vuelta te esperan el patio y la casa donde te alojas.',
    territoryTags: ['La luz del amanecer', 'El mar', 'Las ciudades barrocas'],
    locationLabel: '04 / DÓNDE ESTAMOS', locationTitle: 'Tu estancia\nen Frigintini.',
    addressLabel: 'AQUÍ NOS ENCONTRARÁS', address: ['Via Calanchi 78', 'Frigintini, Modica', 'Sicilia, Italia'],
    map: 'Abrir el mapa', stayLabel: 'TU ESTANCIA',
    stayText: 'En Airbnb puedes consultar las fechas disponibles, los precios y la información de la estancia. Antes de reservar, puedes escribir a Massi desde el anuncio si tienes preguntas sobre la casa.',
    airbnb: 'Ver fechas en Airbnb', external: 'se abre en una pestaña nueva',
    closing: 'Te esperamos\nen Frigintini.',
    footer: 'Una casa familiar en el campo de Módica.', top: 'Volver arriba', privacy: 'Privacidad',
    privacyTitle: 'Navegar con sencillez', privacyText: 'Este sitio no utiliza cookies, herramientas de análisis, formularios ni contenido externo incrustado. Las fotos y las fuentes se sirven desde el propio sitio. Los enlaces a Google Maps y Airbnb abren sitios externos con sus propias políticas de privacidad. Este sitio está alojado en GitHub Pages: GitHub registra las direcciones IP de los visitantes por motivos de seguridad.', close: 'Cerrar',
    notFound: 'Esta página no está en casa.', backHome: 'Volver a la casa',
  },
};
